version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx${DOCKER_CONTAINER_SUFFIX}
    ports:
      - ${DOCKER_PORT_NGINX:-127.0.0.1:80}:80
    volumes:
      - ../.:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql${DOCKER_CONTAINER_SUFFIX}
    restart: unless-stopped
    tty: true
    ports:
      - ${DOCKER_PORT_DB:-127.0.0.1:3306}:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php${DOCKER_CONTAINER_SUFFIX}
    volumes:
      - ../.:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis${DOCKER_CONTAINER_SUFFIX}
    restart: unless-stopped
    ports:
      - ${DOCKER_PORT_REDIS:-127.0.0.1:6379}:6379
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: composer${DOCKER_CONTAINER_SUFFIX}
    volumes:
      - ../.:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer'] #, '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm${DOCKER_CONTAINER_SUFFIX}
    volumes:
      - ../.:/var/www/html:delegated
    ports:
      - ${DOCKER_PORT_NPM:-127.0.0.1:3000}:3000
      - ${DOCKER_PORT_NPM2:-127.0.0.1:3001}:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: artisan${DOCKER_CONTAINER_SUFFIX}
    volumes:
      - ../.:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog${DOCKER_CONTAINER_SUFFIX}
    ports:
      - ${DOCKER_PORT_MAILHOG:-127.0.0.1:1025}:1025
      - ${DOCKER_PORT_MAILHOG2:-127.0.0.1:8025}:8025
    networks:
      - laravel

